# Use postgres/example user/password credentials
version: '3.8'

services:
  db:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8090:8080
